EXECUTE DEPTREE_FILL ('PROCEDURE','user_dev','INCLUIR_CLIENTE');

SELECT NESTED_LEVEL, SCHEMA, TYPE, NAME FROM DEPTREE ORDER BY SEQ#;

-- digitar dentro do begin da procedure user_app.INCLUIR_CLIENTE

CLIENTE_PAC.INCLUIR_CLIENTE(p_ID, p_RAZAO_SOCIAL, p_CNPJ, p_SEGMERCADO_ID, p_FATURAMENTO_PREVISTO);