--- user_app ---

CREATE OR REPLACE PROCEDURE INCLUIR_SEGMENTO (
    p_ID IN SEGMERCADO.ID%type, 
    p_DESCRICAO IN SEGMERCADO.DESCRICAO%type
)
IS
BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, p_DESCRICAO);
END;

-- executar comandos abaixo no user_dev e exeutar procedure acima novamente

GRANT SELECT, INSERT ON SEGMERCADO TO user_app;
CREATE PUBLIC SYNONYM SEGMERCADO FOR user_dev.SEGMERCADO;
GRANT EXECUTE ON EXCEPTION_PAC TO PUBLIC;

-- user_app

EXECUTE INCLUIR_SEGMENTO (NULL, 'SEGMENTO INCLUIDO PELO USUÁRIO USER_APP');

-- user_dev

CREATE PUBLIC SYNONYM EXCEPTION_PAC FOR user_dev.EXCEPTION_PAC;

-- editar a procedure de user_app

CREATE OR REPLACE PROCEDURE INCLUIR_SEGMENTO (
    p_ID IN SEGMERCADO.ID%type, 
    p_DESCRICAO IN SEGMERCADO.DESCRICAO%type
)
IS
BEGIN
    INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (p_ID, p_DESCRICAO);
EXCEPTION
    WHEN EXCEPTION_PAC.e_null THEN
        raise_application_error (-20015, 'Campo do segmento com preechimento obrigatório');
END;

-- user_app

EXECUTE INCLUIR_SEGMENTO (NULL, 'SEGMENTO INCLUIDO PELO USUÁRIO USER_APP');